export const ENGINE_STATUS = {
  IDLE: "IDLE",
  LOADING: "LOADING",
  READY: "READY",
  ERROR: "ERROR",
};

export const ENGINE_GENERATE_STATUS = {
  IDLE: "IDLE",
  INITIALIZATION: "INITIALIZATION",
  READYING_FILE: "READYING_FILE",
  GENERATING: "GENERATING",
  DONE: "DONE",
  ERROR: "ERROR",
};
